version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:1.29.0
    container_name: plex
    network_mode: host
    security_opt:
      - no-new-privileges:true
    #ports:
    #- "32400:32400/tcp"
    #- "3005:3005/tcp"
    #- "8324:8324/tcp"
    #- "32469:32469/tcp"
    #- "1900:1900/udp"
    #- "32410:32410/udp"
    #- "32412:32412/udp"
    #- "32413:32413/udp"
    #- "32414:32414/udp"
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=$CLAIMTOKEN
    volumes:
      - /home/$USER/docker/plex:/config
      - /media/$USER/storage/data:/data
      #- /media/$USER/4TB2/data:/data
      #- /media/$USER/3TB/data:/data 2
      #- /media/$USER/4TB/data:/data 3
    restart: no
